In [91]:
import cv2

><b>cv2.getStructuringElement(type, ksize)</b> outputs a kernel matrix of required <i>`@type`</i> and <i>`@size`</i>
>
>the below cell is self explanatory, run it

In [53]:
kernelellip = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,3))
kernelrect = cv2.getStructuringElement(cv2.MORPH_RECT, (5,5))
kernelcross = cv2.getStructuringElement(cv2.MORPH_CROSS, (5,5))
print(kernelellip,"\n")
print(kernelrect,"\n")
print(kernelcross,"\n")

[[0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]] 

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]] 

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]] 



In [65]:
img = cv2.imread("assets//images//hello.jpg",0)
cv2.imshow("hello",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

><b>cv2.dilate(img, structuringkernel, iterations)</b> widens the white regions of an image
>
><i>`@structuringkernel`</i> defines the way the neighbouring pixels will be used in central pixel calculation
>
><i>`@iterations`</i> the no. of times the operation is done
>
><b>cv2.erode()</b> works just the opposite i.e. it narrows the white regions. it has ecxactly the same parameters as cv2.dilate()

In [42]:
dilate = cv2.dilate(img,kernelrect,iterations=3)
erode = cv2.erode(img,kernelrect,iterations=3)
cv2.imshow("original",img)
cv2.imshow("dilate",dilate)
cv2.imshow("erode",erode)
cv2.waitKey(0)
cv2.destroyAllWindows()

><b>cv2.morphologyEx(img, operation, structuringkernel)</b> used to do some basic morphological operations with the image. what are these operations will be explained soon in the below cells. here we will perform 5 operations
>- `opening` erosion followed by dilation.
>- `closing` opposite of opening, dilation followed by erosion.
>- `morphological gradient` is the difference between a dilation and erosion.
>- `top hat` is the difference between the original (grayscale/single channel) input image and the opening.
>- `black hat` is the difference between the closing and the original (grayscale/single channel) input image.
>
>[morphological operations](https://docs.opencv.org/4.x/d9/d61/tutorial_py_morphological_ops.html) is an amazing explanation of this operations with examples

In [67]:
white_noise = cv2.imread("assets//images//hello_noise_white.jpg",0)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (11,11))
opening = cv2.morphologyEx(white_noise,cv2.MORPH_OPEN,kernel)
cv2.imshow("original",white_noise)
cv2.imshow("opening",opening)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [73]:
black_noise = cv2.imread("assets//images//hello_noise_black.jpg",0)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (11,11))
closing = cv2.morphologyEx(black_noise,cv2.MORPH_CLOSE,kernel)
cv2.imshow("original",black_noise)
cv2.imshow("closing",closing)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [74]:
img = cv2.imread("assets//images//hello.jpg",0)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (11,11))
grad = cv2.morphologyEx(img,cv2.MORPH_GRADIENT,kernel)
cv2.imshow("original",img)
cv2.imshow("morphological gradient",grad)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [83]:
white_noise = cv2.imread("assets//images//hello_noise_white.jpg",0)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (11,11))
tophat = cv2.morphologyEx(white_noise,cv2.MORPH_TOPHAT,kernel)
cv2.imshow("original",white_noise)
cv2.imshow("tophat",tophat)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [84]:
black_noise = cv2.imread("assets//images//hello_noise_black.jpg",0)
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (11,11))
tophat = cv2.morphologyEx(black_noise,cv2.MORPH_BLACKHAT,kernel)
cv2.imshow("original",black_noise)
cv2.imshow("tophat",tophat)
cv2.waitKey(0)
cv2.destroyAllWindows()

><b>Convolutions</b>
>
>![convolutions](assets//images/convolutions.gif)
>![convolutions with padding](assets//images/convolutions%20with%20padding.gif)
>
>for more reading, refer [this](https://pyimagesearch.com/2016/07/25/convolutions-with-opencv-and-python/)

><b>cv2.filter2D(img, ddepth, kernel)</b> use to convolve a <i>`@kernel`</i> with the <i>`@img`</i>
>
><i>`@ddepth`</i> depth of output image. set it to -1 to so that depth of output image becomes equal to depth of input image
>
>for knowing more about its parameters read [doc.py](assets//doc.py) in the assets folder, and search the function in the py file

In [93]:
import numpy as np
kernel = np.array([[0, -1, 0],
                   [-1, 5,-1],
                   [0, -1, 0]])
img = cv2.imread("assets//images//lenna.jpg")
sharp = cv2.filter2D(img, -1, kernel)
cv2.imshow("original",img)
cv2.imshow("sharp",sharp)
cv2.waitKey(0)
cv2.destroyAllWindows()

>here are some example kernels
>
>![kernels](assets//images/examples%20kernels.png)