In [1]:
import cv2
import numpy as np

In [68]:
blank_img = np.zeros((512,512,3),np.uint8)
print(blank_img)

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]


In [69]:
cv2.imshow("blank",blank_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.line(blank_img,(10,10),(200,200),(255,0,0),5)
cv2.imshow("blank",blank_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.rectangle(blank_img,(10,10),(200,200),(0,255,0),5)
cv2.imshow("blank",blank_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.circle(blank_img,(256,256),100,(0,0,255),5)
cv2.imshow("blank",blank_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.ellipse(blank_img,(400,400),(100,50),0,0,360,(255,255,255),5)
cv2.imshow("blank",blank_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
cv2.putText(blank_img,"Hello OpenCV",(220,120),cv2.FONT_HERSHEY_SIMPLEX,1,(54,86,210),5)
cv2.imshow("blank",blank_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
pts = np.array([[250,450],[50,360],[120,360],[100,200]])
pts2 = np.array([[25,45],[50,30],[10,360],[100,20]])
cv2.polylines( blank_img,[pts2,pts],True,(54,36,100),5)
cv2.imshow("blank",blank_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [ ]:
pts3 = np.array([[205,405],[500,30],[100,306],[10,200]])
cv2.fillPoly(blank_img,[pts3],(54,96,35))
cv2.imshow("blank",blank_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [80]:
img = cv2.imread("assets//images//scenary.jpg")
mask = np.zeros(img.shape,np.uint8)
cv2.rectangle(mask,(220,220),(1000,600),(0,0,255),-1)
cv2.imshow("original",img)
cv2.imshow("mask",mask)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [66]:
bitand = cv2.bitwise_and(img,mask)
cv2.imshow("output",bitand)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(np.max(bitand[220:600,220:1000]))
print(np.min(bitand[220:600,220:1000]))

255
0


In [67]:
bitor = cv2.bitwise_or(img,mask)
cv2.imshow("output",bitor)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(np.max(bitor[220:600,220:1000]))
print(np.min(bitor[220:600,220:1000]))

255
255


In [81]:
bitxor = cv2.bitwise_xor(img,mask)
cv2.imshow("output",bitxor)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(np.max(bitxor[220:600,220:1000]))
print(np.min(bitxor[220:600,220:1000]))

255
0


In [152]:
np.random.seed(42)
demo = np.random.randint(0,256,size=(4,4,3),dtype=np.uint8)
mask = np.zeros(demo.shape,np.uint8)
cv2.rectangle(mask,(0,0),(4,4),(255,255,255),-1)
bit = cv2.bitwise_xor(demo,mask)
cv2.imshow("demo",mask)
cv2.imshow("bit",bit)
cv2.waitKey(0)
cv2.destroyAllWindows()
print(bit)

[[[153  35  30]
  [160  76 194]
  [ 21  52 163]
  [252 157  12]]

 [[241 106  10]
  [209 149  11]
  [156  68 184]
  [ 43 102  56]]

 [[ 67  81 190]
  [102 235 211]
  [ 52 103 153]
  [ 41  15 216]]

 [[134 231 221]
  [141  45 190]
  [ 16 216  41]
  [ 11 104 230]]]


In [153]:
demo

array([[[102, 220, 225],
        [ 95, 179,  61],
        [234, 203,  92],
        [  3,  98, 243]],

       [[ 14, 149, 245],
        [ 46, 106, 244],
        [ 99, 187,  71],
        [212, 153, 199]],

       [[188, 174,  65],
        [153,  20,  44],
        [203, 152, 102],
        [214, 240,  39]],

       [[121,  24,  34],
        [114, 210,  65],
        [239,  39, 214],
        [244, 151,  25]]], dtype=uint8)

In [154]:
demo.astype(np.uint32)+bit.astype(np.uint32)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint32)

In [155]:
demo==bit

array([[[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False, False, False],
        [False, False, False]]])